version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo installing maven...
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Build started on `date`
      - mvn install
artifacts:
  files:
    - target/final-java-app-demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes